# Generated by Django 2.2.1 on 2019-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=150)),
                ('write', models.CharField(db_index=True, max_length=150)),
                ('publish', models.TextField(blank=True, db_index=True)),
                ('pages', models.IntegerField(null=True)),
                ('authors', models.TextField(db_index=True, max_length=150)),
            ],
        ),
    ]
