# Generated by Django 2.2.1 on 2019-06-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=150)),
                ('p_type', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('num_pages', models.IntegerField(null=True)),
                ('co_authors', models.TextField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Inform',
        ),
        migrations.AddField(
            model_name='paper',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopus1.Staff'),
        ),
    ]
