# Generated by Django 2.2.1 on 2019-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0002_auto_20190604_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
    ]
