# Generated by Django 2.2.1 on 2019-06-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0004_auto_20190604_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scopus1.Staff'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='p_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scopus1.P_type'),
        ),
    ]
