# Generated by Django 2.2.1 on 2019-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0005_auto_20190604_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='co_authors',
            field=models.TextField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
