# Generated by Django 2.2.1 on 2019-06-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0006_auto_20190604_1615'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='paper',
            order_with_respect_to='author_id',
        ),
    ]
