# Generated by Django 2.2.1 on 2019-06-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0007_auto_20190605_1842'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='paper',
            order_with_respect_to=None,
        ),
    ]
