# Generated by Django 2.2.1 on 2019-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0008_auto_20190605_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='unreaded',
            field=models.BooleanField(default=True),
        ),
    ]
