# Generated by Django 2.2.1 on 2019-06-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0009_paper_unreaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='unreaded',
            new_name='unread',
        ),
    ]
