# Generated by Django 2.1.2 on 2019-06-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0010_auto_20190606_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='scopus_author_id',
            field=models.IntegerField(default=0),
        ),
    ]
