# Generated by Django 2.1.2 on 2019-06-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0011_staff_scopus_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopus1.Staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='co_authors',
        ),
        migrations.AddField(
            model_name='authors',
            name='p_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopus1.Paper'),
        ),
    ]
