# Generated by Django 2.1.2 on 2019-06-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0012_auto_20190608_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='authors',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='p_title',
        ),
        migrations.AddField(
            model_name='authors',
            name='f_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='authors',
            name='l_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='authors',
            name='m_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='authors',
            name='scopus_author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authors',
            name='staff_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='p_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopus1.P_type'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='authored',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopus1.Authors'),
        ),
        migrations.AddField(
            model_name='authored',
            name='p_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopus1.Paper'),
        ),
    ]
