# Generated by Django 2.1.2 on 2019-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopus1', '0013_auto_20190608_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_type',
            name='type_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
